### ISSUE TITLE
Typo in Returnmanager.py

### ISSUE THREAD

**Issue by mtbsteve** [OpenSolo/shotmanager#8]
There is a small typo in line 81 causing a callback error - instead of "false" it should state "**F**alse"
self.shotmgr.rcMgr.enableRemapping( false )
In my understanding this statement isn't needed anyway and can be deleted.

**Comment by peterbarker** [comment]
@mtbsteve Are you in a position to create a pull request to fix this?  The trick is testing it, not making the trivial fix you suggest :-)

**Comment by davidbuzz** [comment]
PR welcome!
